// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBat() {
  return window['go']['main']['App']['AddBat']();
}

export function EnsureHarness() {
  return window['go']['main']['App']['EnsureHarness']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function OpenHarnessBrowser() {
  return window['go']['main']['App']['OpenHarnessBrowser']();
}

export function QuitApp(arg1) {
  return window['go']['main']['App']['QuitApp'](arg1);
}

export function RemoveBat(arg1) {
  return window['go']['main']['App']['RemoveBat'](arg1);
}

export function SetHarnessCmd(arg1) {
  return window['go']['main']['App']['SetHarnessCmd'](arg1);
}

export function SkipWait() {
  return window['go']['main']['App']['SkipWait']();
}

export function StartBatOnly(arg1) {
  return window['go']['main']['App']['StartBatOnly'](arg1);
}

export function StartModel(arg1) {
  return window['go']['main']['App']['StartModel'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopModelOnly() {
  return window['go']['main']['App']['StopModelOnly']();
}
