// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBat():Promise<string>;

export function EnsureHarness():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetSysInfo():Promise<main.SysInfo>;

export function ListPresets():Promise<Array<main.Preset>>;

export function OpenHarnessBrowser():Promise<void>;

export function QuitApp(arg1:boolean):Promise<void>;

export function RemoveBat(arg1:string):Promise<void>;

export function SetHarnessCmd(arg1:string):Promise<void>;

export function SkipWait():Promise<void>;

export function StartBatOnly(arg1:string):Promise<string>;

export function StartModel(arg1:string):Promise<string>;

export function Status():Promise<Record<string, boolean>>;

export function StopAgent():Promise<void>;

export function StopAll():Promise<void>;

export function StopModelOnly():Promise<void>;
